# version: '3'
# services:
#   db:
#     image: mysql:latest
#     environment: 
#       MYSQL_DATABASE: lamp_docker
#       MYSQL_USER: lamp_docker
#       MYSQL_PASSWORD: password
#       MYSQL_ALLOW_EMPTY_PASSWORD: 1
#     volumes:
#       - "./db:/docker-entrypoint-initdb.d"
#     networks:
#       - lamp-docker
#   www:
#     depends_on:
#       - db
#     image: .
#     volumes:
#       - "./:/var/www/html"
#     ports:
#       - 80:80
#       - 443:443
#     networks:
#       - lamp-docker
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - 8001:80
#     environment:
#       - PMA_HOST=db
#       - PMA_PORT=3306
#     networks:
#       - lamp-docker
# networks:
#   lamp-docker:
#     driver: bridge

version: "4"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: dbname
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            # - persistent:/var/lib/mysql
        networks:
            - default
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html
        links:
            - db
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
volumes:
    persistent: